name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint frontend only
        run: npm run lint --workspace=frontend

      - name: Build frontend
        run: npm run build --workspace=frontend

      - name: Build backend
        run: npm run build --workspace=backend
